version: "3.8"
services:
  app:
    restart: always
    container_name: Book_Review
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      # Conexion al container de la base de datos
      - DATABASE_URL=mysql://root:root@mysql:3306/bookreview
      # Codigo generado ref: env.example
      - NEXTAUTH_SECRET=
      - NEXTAUTH_URL=http://localhost:3000
      # Cuenta de gmail para correo ref: env.example
      - GMAIL_NODEMAILER_EMAIL=
      # Contrasena de gmail para correo ref: env.example
      - GMAIL_NODEMAILER_PASSWORD=
    depends_on:
      - db
    networks:
      - connection
  db:
    container_name: mysql
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    networks:
      - connection
    environment:
      MYSQL_DATABASE: bookreview
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-db:/var/lib/mysql

networks:
  connection:
    driver: bridge

volumes:
  my-db:
    driver: local
