import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "@/utils/api";
import BookSchema from "@/components/Book";
import { useState } from "react";
import { type Book } from "@prisma/client";
import SideMenu from "@/components/SideMenu";
import { useRouter } from "next/router";
import { useToast } from "@/hooks/use-toast";
import ProfileCard from "@/components/ProfileCard";

import { getServerAuthSession } from "../../server/auth";
import type { GetServerSideProps } from "next";
import { Avatar, AvatarImage, AvatarFallback } from "@radix-ui/react-avatar";
import { Mail } from "lucide-react";
import { Button } from "@/components/ui/button";

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  // get session if not session do not give anything
  const session = await getServerAuthSession(ctx);
  if (!session) {
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };
  }
  return {
    props: {
      session,
    },
  };
};

const Profile: NextPage = () => {
  // Session from back so it is already loaded
  const { data: session } = useSession();
  if (session) {
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen  flex-col items-center justify-center bg-gradient-to-b from-[#e25706] to-[#9e7830] pb-10">
          <div className="m-5 my-10 flex w-72 flex-col items-center justify-center gap-2 rounded-xl bg-white/70 p-4 lg:w-96">
            <h1 className="text-2xl font-semibold">This is your profile</h1>
            <p className="text-center">
              As well mine. With all my social media.
            </p>
            <p className="text-center">
              By the way this route is protected with{" "}
              <span className="font-semibold">getServerSideProps</span> that
              means it only shows if you{"'"}re authenticated. And the
              validation is made on serverside thanks to{" "}
              <span className="font-semibold">NextJs</span>
            </p>
          </div>
          <div className="flex  w-3/4 flex-col justify-around gap-y-20 lg:flex-row lg:gap-y-0">
            <ProfileCard session={session} />
            <Link href="/" className="flex w-full items-center justify-center">
              <Button className="w-full lg:w-32">Go Home</Button>
            </Link>

            <div className="max-w-md rounded-md bg-gray-50 p-8 text-gray-800 shadow-lg shadow-black/70 sm:flex sm:space-x-6">
              <div className="mb-6 h-44 w-full flex-shrink-0 rounded-full border-2 border-t-red-600 border-b-yellow-600 border-r-cyan-600 border-l-green-600 sm:mb-0 sm:h-32 sm:w-32">
                <Avatar>
                  <AvatarImage
                    className="rounded-full"
                    src={"https://avatars.githubusercontent.com/u/64233636?v=4"}
                  />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
              </div>
              <div className="flex flex-col space-y-4">
                <div>
                  <h2 className="text-2xl font-semibold">Alcaen</h2>
                  <span className="text-sm font-medium text-gray-700">
                    Developer
                  </span>
                </div>
                <div className="space-y-1">
                  <span className="flex items-center space-x-2">
                    <Mail />
                    <span className="font-semibold text-gray-600">
                      alcaen.dev@gmail.com
                    </span>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </main>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-row items-center justify-center bg-gradient-to-b from-[#e25706] to-[#9e7830]">
          <div className="flex w-3/4 justify-around"></div>
        </main>
      </>
    );
  }
};

export default Profile;
